spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "bepis.lmao@gmail.com"
    password: "hacknu2021"
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hacknu
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

